### ISSUE TITLE
We're not ignoring fields that the server doesn't know about as required by the spec

### ISSUE THREAD

**Issue by ussmith** [PennState/SCIMple-Identity#14] opened 2016-04-30 21:09 UTC
During unmarshalling we should ignore things that don't unmarshall into our objects.

**Comment by ussmith** [comment] 2016-04-30 21:11
http://www.baeldung.com/jackson-deserialize-json-unknown-properties

**Comment by smoyer64** [comment] 2016-05-02 15:36
Since the @JsonAnySetter method in ScimResource tries to match unknown fields to registered extensions, unknown fields (of any type) will be parsed by this code.  The error was caused by an NPE thrown when no extension was registered for a given attribute name.  Fixed with commit b97a7654b9b3ff79554cffe92b381a8ba8d6dfbf.

**Closed by smoyer64** 2016-05-02 15:36 UTC
